using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace YonatanMankovich.PlaylistPlanner
{
    public class Playlist
    {
        public TimeSpan Duration { get; private set; }
        private List<MusicFile> MusicFiles { get; set; } = new List<MusicFile>();

        public void AddMusicFile(MusicFile musicFile)
        {
            MusicFiles.Add(musicFile);
            Duration += musicFile.Duration;
        }

        public void RemoveMusicFile(MusicFile musicFile)
        {
            if (MusicFiles.Contains(musicFile))
            {
                MusicFiles.Remove(musicFile);
                Duration -= musicFile.Duration;
            }
        }

        public int GetSize()
        {
            return MusicFiles.Count;
        }

        public IEnumerable<MusicFile> GetMusicFiles()
        {
            foreach (MusicFile musicFile in MusicFiles)
                yield return musicFile;
        }

        public void Save(string path, bool isRelative)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("#EXTM3U");
            sb.AppendLine($"#EXTINF:{Math.Round(Duration.TotalSeconds)},Generated by PlaylistPlanner by Yonatan Mankovich");
            foreach (MusicFile musicFile in MusicFiles)
                sb.AppendLine(isRelative ? Path.GetFileName(musicFile.Path) : musicFile.Path);
            File.WriteAllText(path, sb.ToString());
        }

        public void Play()
        {
            string fileName = "Playlist.m3u";
            Save(fileName, false);
            System.Diagnostics.Process.Start(fileName);
        }

        public void Shuffle()
        {
            Random random = new Random();
            int n = GetSize();
            while (n > 1)
            {
                n--;
                int k = random.Next(n + 1);
                MusicFile value = MusicFiles[k];
                MusicFiles[k] = MusicFiles[n];
                MusicFiles[n] = value;
            }
        }
    }
}